blog/urls.py
from django.conf.urls import url


urlpatterns = [
    url(r'^about/$', 'blog.views.about', name='about'),
    url(r'^photos/$', 'blog.views.photos', name='photos'),

    url(r'^p/(?P<slug>[\w-]+)/$', 'blog.views.post', name='post'),
    url(r'^$', 'blog.views.home', name='home'),
]

cms/urls.py
from django.conf.urls import url


urlpatterns = [
    url(r'^posts/$', 'cms.views.post_list', name='post_list'),
    url(r'^new_post/$', 'cms.views.new_post', name='new_post'),
    url(r'^update_post/(?P<pk>\d+)/$', 'cms.views.update_post', name='update_post'),
    url(r'^delete_post/(?P<pk>\d+)/$', 'cms.views.delete_post', name='delete_post'),

    url(r'^photos/$', 'cms.views.photo_list', name='photo_list'),
    url(r'^new_photo/$', 'cms.views.new_photo', name='new_photo'),
    url(r'^update_photo/(?P<pk>\d+)/$', 'cms.views.update_photo', name='update_photo'),
    url(r'^delete_photo/(?P<pk>\d+)/$', 'cms.views.delete_photo', name='delete_photo'),
    url(r'^set_photo_order/(?P<pk>\d+)/$', 'cms.views.set_photo_order', name='set_photo_order'),

    url(r'^$', 'cms.views.post_list', name='post_list'),
]

javiman/urls.py
from django.conf.urls import include, url

import session_csrf
session_csrf.monkeypatch()

urlpatterns = [
    url(r'^_ah/', include('djangae.urls')),
    url(r'^csp/', include('cspreports.urls')),
    url(r'^auth/', include('djangae.contrib.gauth.urls', namespace='login')),

    url(r'^cms/', include('cms.urls', namespace='cms')),
    url(r'', include('blog.urls', namespace='blog')),
]

blog/models.py
import datetime
from django.utils.text import slugify
from django.db import models

from markupfield.fields import MarkupField


class PostManager(models.Manager):
    def get_queryset(self):
        return super(PostManager, self).get_queryset()

    def published(self):
        return super(PostManager, self).get_queryset().filter(is_published=True)


class Post(models.Model):
    title = models.CharField(max_length=128)
    created = models.DateTimeField(null=True)
    updated = models.DateTimeField(null=True)
    slug = models.CharField(max_length=128, blank=True)
    body = MarkupField(default_markup_type='markdown')
    is_published = models.BooleanField(default=False)
    objects = PostManager()

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        if not self.id and not self.created:
            self.created = datetime.datetime.now()
        self.updated = datetime.datetime.now()
        super(Post, self).save(*args, **kwargs)

    class Meta:
        ordering = ('-created',)


class PhotoManager(models.Manager):
    def get_queryset(self):
        return super(PhotoManager, self).get_queryset()

    def published(self):
        return super(PhotoManager, self).get_queryset().filter(is_published=True)


class Photo(models.Model):
    title = models.CharField(max_length=256, blank=True)
    subtitle = models.CharField(max_length=256, blank=True)
    url = models.CharField(max_length=256)
    is_published = models.BooleanField(default=False)
    order = models.IntegerField(default=0)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    objects = PhotoManager()

    class Meta:
        ordering = ('order', '-created',)

    def __unicode__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.pk:
            for photo in Photo.objects.filter(order__gte=self.order):
                photo.order += 1
                photo.save()
        super(Photo, self).save(*args, **kwargs)

    def decrease_order_and_save(self):
        self.order = max(0, self.order - 1)
        # Get the photo with the same order as this photo and increase its order.
        photo_qs = Photo.objects.filter(order=self.order)
        if photo_qs.exists():
            photo = photo_qs[0]
            photo.order = self.order + 1
            photo.save()
        self.save()

    def increase_order_and_save(self):
        self.order += 1
        # Get the photo with the same order as this photo and decrease its order.
        photo_qs = Photo.objects.filter(order=self.order)
        if photo_qs.exists():
            photo = photo_qs[0]
            photo.order = self.order - 1
            photo.save()
        self.save()

    def get_flickr_preview(self):
        """
        This will only work for jpeg images stored in flickr.
        Given a url like:
            //farm1.staticflickr.com/702/20638346971_1c14fc9bff_l.jpg,
        this will return something like:
            //farm1.staticflickr.com/702/20638346971_1c14fc9bff_m.jpg
        """
        image_url = self.url[:-6]
        return '{}_m.jpg'.format(image_url)

    def get_640(self):
        """
        This will only work for jpeg images stored in flickr.
        Given a url like:
            //farm1.staticflickr.com/702/20638346971_1c14fc9bff_l.jpg,
        this will return something like:
            //farm1.staticflickr.com/702/20638346971_1c14fc9bff_z.jpg
        """
        image_url = self.url[:-6]
        return '{}_z.jpg'.format(image_url)

blog/views.py
import json

from django.core.cache import cache
from django.core.urlresolvers import reverse
from django.shortcuts import redirect
from django.views.generic import DetailView, ListView, TemplateView
import requests

from blog.models import Post, Photo


class HomeView(ListView):
    model = Post
    paginate_by = 3
    template_name = 'blog/home.html'

    def get_queryset(self):
        return self.model.objects.published()

home = HomeView.as_view()


class PostView(DetailView):
    model = Post
    template_name = 'blog/post.html'
    slug_field = 'slug'

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()

        if not self.object.is_published:
            return redirect(reverse('blog:home'))

        context = self.get_context_data(object=self.object)
        return self.render_to_response(context)

post = PostView.as_view()


class PhotoListView(ListView):
    model = Photo
    paginate_by = 12
    template_name = 'blog/photos.html'

    def get_queryset(self):
        return self.model.objects.published()

photos = PhotoListView.as_view()


class AboutView(TemplateView):
    template_name = 'blog/about.html'

about = AboutView.as_view()

templates/blog/about.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Javi Manzano - Web Developer</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <link rel="shortcut icon" type="image/x-icon" href="{% static 'img/favicon.png' %}" />

    <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,700,300" rel="stylesheet" type="text/css">
    <link href="{% static 'css/about/main.css' %}" rel="stylesheet">
</head>

<body>
    <header>
        <a href="{% url 'blog:home' %}"><i class="icon-arrow-left large-font margin-right10"></i> Back to the blog</a>
        <div class="row">
            <div class="two-thirds">
                <div class="title-container align-center">
                    <h1>Hello World!</h1>
                    <p class="subtitle">My name is <strong>Javi Manzano</strong> and I am a Web Developer</p>
                </div>
            </div>
            <div class="one-third">
                <img class="mill-img" src="{% static 'img/mill.png' %}">
                <a href="http://xkcd.com/">
                    <img title="" src="{% static 'img/stick-man.png' %}" class="stick-man-img">
                </a>
                <em class="stick-man-subtitle">And I love xkcd</em>
            </div>
        </div>
    </header>

    <div role="main">
        <section>
            <div class="row">
                <div class="one-quarter">
                    <h2>HTML</h2>
                    <p>I build websites and, most of the times, they have to be well structured. As I usually say, <em>I feel better writing a document in HTML rather than using Microsoft Word</em>.</p>
                </div>
                <div class="one-quarter">
                    <h2>
                        <span class="floating-more"><span class="floating-more-two">C</span><span class="floating-more">S</span><span class="floating-more-two">S</span></span>
                    </h2>
                    <p>Because not everything must be <span class="red">red</span>,  <span class="green">green</span> or <span class="blue">blue</span>, <span class="bold">bold</span> or <span class="underline">underline</span>. CSS makes the web as <span class="pulse">awesome</span> as we know it these days. SASS is my preprocessor of choice.</p>
                </div>
                <div class="one-quarter">
                    <h2>JavaScript</h2>
                    <p>One of the first web-programming languages I learnt to use along with PHP. At first glance I didn't like it much, but then I realized <em>JavaScript didn't suck, I was just doing it wrong</em>.</p>
                </div>
                <div class="one-quarter">
                    <h2>Python</h2>
                    <p>Little by little, Python has become the backend programming language in which more lines I've ever coded. I can't even remember my old PHP times, which is cool.</p>
                </div>
            </div>
            <div class="row">
                <div class="one-quarter">
                    <h2>Django</h2>
                    <p>The Django web framework has changed the way I feel about web development. I can use my BE language of preference with it, Python, and for me it's the perfect framework for the web.</p>
                </div>
                <div class="one-quarter">
                    <h2>Backbone.js</h2>
                    <p>When you do some JavaScript for a while, at some point you realise you need to give a proper organization to your JavaScript. That's where Backbone.js comes in.</p>
                </div>
                <div class="one-quarter">
                    <h2>AngularJS</h2>
                    <p>But sometimes happen that even Backbone.js starts looking <em>confusing</em>. Then AngularJS comes in. Forget about event bindings, extend your HTML markup and dominate the interwebs with AngularJS.</p>
                </div>
                <div class="one-quarter">
                    <h2>Android</h2>
                    <p>I've recently started learning JAVA to build my own Android apps. It's not something I'd like to do for a living – for now at least–, but it is something I've been wanting to do as a hobby since Android came out.</p>
                </div>
            </div>
        </section>
        <section>
            <div class="row">
                <div class="one-half">
                    <h2>Working Experience</h2>
                    <ul>
                        <li>Software Enginner at <a target="_blank" href="http://p.ota.to/">Potato London Ltd</a> (London, UK) - <em>August 2012 to Present</em></li>
                        <li>Web Developer at <a target="_blank" href="http://i2mapp.com/?lang=en">i2MApp Innovación en Movilidad S.L.</a> (San Sebastián, Spain) - <em>Jul 2010 to Jul 2012</em></li>
                    </ul>
                </div>
                <div class="one-half">
                    <h2>Academics</h2>
                    <ul>
                        <li>UPV-EHU, Universidad del País Vasco. (San Sebastián, Spain) Bachelor of Computer Science - <em>Sep 2007 to May 2012</em></li>
                        <li>Course about software security - <em>May 2011</em></li>
                        <li>Course about Django, a web framework based in Python - <em>Mar 2011</em></li>
                    </ul>
                </div>
            </div>
        </section>
        <section>
            <div class="row">
                <div class="one-half">
                    <h2>Some stuff</h2>
                    <ul>
                        <li><a target="_blank" class="bold" href="https://github.com/jgasteiz/">Github</a> - I like to work on small pet projects and most of them are in my github. Nothing too fancy, just small things to keep me entertained. Most of the stuff there is web, but I've been working on <a target="_blank" href="https://play.google.com/store/apps/developer?id=Javi+Manzano">a couple of small Android applications</a> recently.</li>
                        <li><a target="_blank" class="bold" href="http://larevolta.me">Fuzzing</a> - Photography portfolio site I've built for a friend using a CMS I've developed using Django 1.6. <a target="_blank" href="https://github.com/jgasteiz/fuzzing">View on github</a></li>
                        <li><a target="_blank" class="bold" href="http://javimanzano.me/colors/">Guess the Color</a> - An afternoon made game for hardcore web developers & designers using HTML, a bit of CSS and some JavaScript. <a target="_blank" href="https://github.com/jgasteiz/Guess-the-color">View on github</a></li>
                        <li><a target="_blank" class="bold" href="https://p.ota.to/work/">Potato projects</a> - Most of the work I do is for Potato London, check their work section and see what kind of stuff we do there. Fun stuff, mostly.</li>
                    </ul>
                </div>
                <div class="one-half">
                    <h2>Other hobbies</h2>
                    <ul>
                        <li>Live concerts & listening to tons of music.</li>
                        <li>I will not hide I enjoy beer. <a target="_blank" href="https://vimeo.com/40818571">A lot.</a></li>
                        <li>Reading a book/comic.</li>
                        <li>Playing the guitar.</li>
                        <li>Riding my bike - when I used to live in Spain, at least.</li>
                    </ul>
                </div>
            </div>
        </section>
    </div>

    <footer>
        <div class="row align-center">
            <div class="one-quarter">
                <a class="icon social-link" target="_blank" href="http://github.javiman.com">
                    <i class="icon-github large-font margin-right10"></i>
                    github.javiman.com
                </a>
            </div>
            <div class="one-quarter">
                <a class="icon social-link" target="_blank" href="http://twitter.javiman.com">
                    <i class="icon-twitter large-font margin-right10"></i>
                    twitter.javiman.com
                </a>
            </div>
            <div class="one-quarter">
                <a class="icon social-link" target="_blank" href="http://linkedin.javiman.com">
                    <i class="icon-linkedin large-font margin-right10"></i>
                    linkedin.javiman.com
                </a>
            </div>
            <div class="one-quarter">
                <a class="icon social-link" target="_blank" href="http://blog.javiman.com">
                    <i class="icon-rss large-font margin-right10"></i>
                    blog.javiman.com
                </a>
            </div>
        </div>
        <div class="row align-center">
            <p>Need more personal interaction?</p>
            <a class="icon social-link" target="_blank" href="mailto:javi.manzano.oller@gmail.com">
                <i class="icon-envelope-alt large-font margin-right10"></i>
                Send me an email
            </a>
        </div>
    </footer>
</body>
</html>

templates/blog/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="initial-scale=1, maximum-scale=1">

    <title>Fuzzing the Web</title>

    <link rel="shortcut icon" type="image/x-icon" href="{% static 'img/facvicon.png' %}">

    <link href="https://fonts.googleapis.com/css?family=PT+Serif:regular,italic,bold,bolditalic" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="{% static 'css/normalize.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/main.css' %}"/>
</head>
<body class="{% block body_class %}{% endblock body_class %}">
    <header id="banner" class="main-header">
        <h1 class="site-name">
            <a href="/">
                Fuzzing the Web
            </a>
        </h1>
        <h2 class="site-subtitle">Javi Manzano's blog</h2>
    </header>
    <nav id="navigation" class="main-nav">
        <ul class="main-menu">
            <li><a href="{% url 'blog:home' %}">Blog</a></li>
            {# <li><a href="/archives/">Archives</a></li> #}
            <li><a href="{% url 'blog:photos' %}">Photos</a></li>
            <li><a href="{% url 'blog:about' %}">About</a></li>
        </ul>
    </nav>
    <div role="main">
        {% block content %}{% endblock content %}
    </div>
    <footer class="main-footer">
        <p>Powered by <a target="_blank" href="https://github.com/potatolondon/djangae">Djangae</a>.</p>
        <p>Me, elsewhere: <a href="https://twitter.com/_javiman" target="_blank">Twitter</a>, <a href="https://github.com/jgasteiz/" target="_blank">Github</a>, <a target="_blank" href="https://www.flickr.com/photos/jgasteiz/">Flickr</a>.</p>
    </footer>

    {% block extra_js %}{% endblock extra_js %}
</body>
</html>

templates/blog/home.html
{% extends 'blog/base.html' %}

{% block content %}
    {% for post in post_list %}
        <article class="post">
            <header>
                <h1 class="entry-title"><a href="{% url 'blog:post' post.slug %}">{{ post.title }}</a></h1>
                <abbr class="published" title="{{ post.created }}">{{ post.created }}</abbr>
            </header>
            <div>{{ post.body }}</div>
        </article>
    {% empty %}
        <article class="post">
            <header>
                <h1 class="entry-title">There are no posts yet</h1>
            </header>
        </article>
    {% endfor %}

    <div class="pagination">
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a href="?page={{ page_obj.previous_page_number }}">previous</a>
            {% endif %}

            <span class="current">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
            </span>

            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">next</a>
            {% endif %}
        </span>
    </div>
{% endblock content %}

templates/blog/photos.html
{% extends 'blog/base.html' %}
{% load static %}

{% block body_class %}body--photos{% endblock body_class %}

{% block content %}
    <header class="photos-header">
        <p>The following pictures have been taken from <a target="_blank" href="https://www.flickr.com/photos/jgasteiz/">my flickr profile</a>.</p>
    </header>

    {% spaceless %}
    <div class="photos-container">
    {% for photo in photo_list %}
        <section class="photo">
            <img class="photo__image js-photo"
                 src="{{ photo.get_640 }}"
                 alt="{{ photo.title }}"
                 title="{{ photo.title }}"
                 data-src="{{ photo.url }}"
                 data-title="{{ photo.title }}"
                 data-subtitle="{{ photo.subtitle }}"
                 >
        </section>
    {% empty %}
        <h1>There are no photos yet</h1>
    {% endfor %}
    </div>
    {% endspaceless %}

    <div class="pagination">
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a href="?page={{ page_obj.previous_page_number }}">previous</a>
            {% endif %}

            <span class="current">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
            </span>

            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">next</a>
            {% endif %}
        </span>
    </div>
{% endblock content %}

{% block extra_js %}
    <script src="//code.jquery.com/jquery-1.11.3.min.js"></script>
    <script src="{% static 'js/photos.js' %}"></script>
{% endblock extra_js %}

templates/blog/post.html
{% extends 'blog/base.html' %}

{% block content %}
    <article class="post">
        <header>
            <h1 class="entry-title">{{ post.title }}</h1>
            <abbr class="published" title="{{ post.created }}">
                {{ post.created }}
            </abbr>
        </header>
        <div>{{ post.body }}</div>
        <footer></footer>
    </article>
{% endblock content %}