cms/urls.py
from django.conf.urls import url


urlpatterns = [
    url(r'^posts/$', 'cms.views.post_list', name='post_list'),
    url(r'^new_post/$', 'cms.views.new_post', name='new_post'),
    url(r'^update_post/(?P<pk>\d+)/$', 'cms.views.update_post', name='update_post'),
    url(r'^delete_post/(?P<pk>\d+)/$', 'cms.views.delete_post', name='delete_post'),

    url(r'^photos/$', 'cms.views.photo_list', name='photo_list'),
    url(r'^new_photo/$', 'cms.views.new_photo', name='new_photo'),
    url(r'^update_photo/(?P<pk>\d+)/$', 'cms.views.update_photo', name='update_photo'),
    url(r'^delete_photo/(?P<pk>\d+)/$', 'cms.views.delete_photo', name='delete_photo'),
    url(r'^set_photo_order/(?P<pk>\d+)/$', 'cms.views.set_photo_order', name='set_photo_order'),

    url(r'^$', 'cms.views.post_list', name='post_list'),
]

javiman/urls.py
from django.conf.urls import include, url

import session_csrf
session_csrf.monkeypatch()

urlpatterns = [
    url(r'^_ah/', include('djangae.urls')),
    url(r'^csp/', include('cspreports.urls')),
    url(r'^auth/', include('djangae.contrib.gauth.urls', namespace='login')),

    url(r'^cms/', include('cms.urls', namespace='cms')),
    url(r'', include('blog.urls', namespace='blog')),
]

cms/models.py
from django.db import models

# Create your models here.

cms/forms.py
from django import forms
from blog.models import Post, Photo


class PostForm(forms.ModelForm):
    class Meta:
        fields = ('title', 'slug', 'body', 'is_published', 'created',)
        model = Post


class PhotoForm(forms.ModelForm):
    class Meta:
        fields = ('title', 'subtitle', 'url', 'is_published', 'order',)
        model = Photo

cms/views.py
from django.core.urlresolvers import reverse, reverse_lazy
from django.shortcuts import redirect
from django.views.generic import CreateView, UpdateView, DeleteView, View, ListView
from google.appengine.api import users

from blog.models import Post, Photo
from cms.forms import PostForm, PhotoForm


class RestrictedAccessMixin(object):
    def dispatch(self, *args, **kwargs):
        if not users.is_current_user_admin():
            login_url = '{}?next={}'.format(
                reverse('login:djangae_login_redirect'),
                reverse('cms:post_list')
            )
            return redirect(login_url)
        return super(RestrictedAccessMixin, self).dispatch(*args, **kwargs)

    def get_context_data(self, *args, **kwargs):
        ctx = super(RestrictedAccessMixin, self).get_context_data(*args, **kwargs)
        ctx['user_email'] = users.get_current_user()
        return ctx


class PostListView(RestrictedAccessMixin, ListView):
    model = Post
    template_name = 'cms/post_list.html'

post_list = PostListView.as_view()


class NewPostView(RestrictedAccessMixin, CreateView):
    form_class = PostForm
    model = Post
    success_url = reverse_lazy('cms:post_list')
    template_name = 'cms/post_form.html'

new_post = NewPostView.as_view()


class UpdatePostView(RestrictedAccessMixin, UpdateView):
    form_class = PostForm
    model = Post
    success_url = reverse_lazy('cms:post_list')
    template_name = 'cms/post_form.html'

update_post = UpdatePostView.as_view()


class DeletePostView(RestrictedAccessMixin, DeleteView):
    model = Post
    success_url = reverse_lazy('cms:post_list')
    template_name = 'cms/post_confirm_delete.html'

delete_post = DeletePostView.as_view()


class PhotoListView(RestrictedAccessMixin, ListView):
    model = Photo
    template_name = 'cms/photo_list.html'

photo_list = PhotoListView.as_view()


class NewPhotoView(RestrictedAccessMixin, CreateView):
    form_class = PhotoForm
    model = Photo
    success_url = reverse_lazy('cms:photo_list')
    template_name = 'cms/photo_form.html'

new_photo = NewPhotoView.as_view()


class UpdatePhotoView(RestrictedAccessMixin, UpdateView):
    form_class = PhotoForm
    model = Photo
    success_url = reverse_lazy('cms:photo_list')
    template_name = 'cms/photo_form.html'

update_photo = UpdatePhotoView.as_view()


class DeletePhotoView(RestrictedAccessMixin, DeleteView):
    model = Photo
    success_url = reverse_lazy('cms:photo_list')
    template_name = 'cms/photo_confirm_delete.html'

delete_photo = DeletePhotoView.as_view()


class SetPhotoOrderView(RestrictedAccessMixin, View):
    model = Photo

    def post(self, request, *args, **kwargs):
        photo = self.model.objects.get(pk=kwargs.get('pk'))
        order_modifier = int(request.POST.get('order_modifier'))
        if order_modifier > 0:
            photo.increase_order_and_save()
        else:
            photo.decrease_order_and_save()
        photo.save()
        return redirect('cms:photo_list')

set_photo_order = SetPhotoOrderView.as_view()

templates/cms/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="initial-scale=1, maximum-scale=1">

    <title>Fuzzing the Web CMS</title>

    <link rel="shortcut icon" type="image/x-icon" href="{% static 'img/facvicon.png' %}">

    <link rel="stylesheet" href="{% static 'vendor/material-design-lite/material.min.css' %}"/>
    <script src="{% static 'vendor/material-design-lite/material.min.js' %}"></script>
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="{% static 'css/cms.css' %}"/>
</head>
<body>
    <!-- Always shows a header, even in smaller screens. -->
    <div class="mdl-layout mdl-js-layout mdl-layout--fixed-header">
        <header class="mdl-layout__header">
            <div class="mdl-layout__header-row">
                <span class="mdl-layout-title">Fuzzing the Web CMS</span>
                <div class="mdl-layout-spacer"></div>
                <nav class="mdl-navigation mdl-layout--large-screen-only">
                    <a href="{% url 'cms:post_list' %}" class="mdl-navigation__link">Post list</a>
                    <a href="{% url 'cms:photo_list' %}" class="mdl-navigation__link">Photos</a>
                </nav>
            </div>
        </header>

        <div class="mdl-layout__drawer">
            <span class="mdl-layout-title">Title</span>
            <nav class="mdl-navigation">
                <a href="{% url 'cms:post_list' %}" class="mdl-navigation__link">Post list</a>
                <a href="{% url 'cms:photo_list' %}" class="mdl-navigation__link">Photos</a>
            </nav>
        </div>
        <main class="mdl-layout__content">
            {% block content %}{% endblock content %}
        </main>
    </div>

    {% block bodyend %}{% endblock bodyend %}
</body>
</html>

templates/cms/flickr_form.html
{% extends 'cms/base.html' %}
{% load form_tags %}

{% block content %}
    <div class="mdl-grid">
        <div class="mdl-cell mdl-cell--4-col">
            <form action="" method="post">
                {% csrf_token %}
                {% for field in form %}
                    <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
                        {{ field|add_css_class:'mdl-textfield__input' }}
                        <label for="{{ field.id_for_label }}" class="mdl-textfield__label">{{ field.label }}</label>

                        {% if field.errors %}
                            {% for error in field.errors %}
                            <span class="mdl-textfield__error">{{ error }}</span>
                            {% endfor %}
                        {% endif %}
                    </div>
                {% endfor %}

                <input type="submit" class="mdl-button mdl-js-button mdl-button--raised mdl-button--colored" value="Save">
                <a class="mdl-button mdl-js-button mdl-button--raised" href="{% url 'cms:flickr' %}">Cancel</a>
            </form>
        </div>
    </div>
{% endblock content %}

{% block bodyend %}{% endblock bodyend %}

templates/cms/flickr_settings.html
{% extends 'cms/base.html' %}

{% block content %}
    <table class="mdl-data-table mdl-shadow--2dp">
        <thead>
            <tr>
                <th>Api key</th>
                <th>User id</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>{{ flickr_settings.api_key }}</td>
                <td>{{ flickr_settings.user_id }}</td>
                <td><a href="{% url 'cms:update_flickr' flickr_settings.pk %}">Update</a></td>
            </tr>
        </tbody>
    </table>
{% endblock content %}

templates/cms/photo_confirm_delete.html
{% extends 'cms/base.html' %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        <p>Are you sure you want to delete this photo?</p>
        <a class="mdl-button mdl-js-button mdl-button--raised" href="{% url 'cms:photo_list' %}">Cancel</a>
        <input type="submit" class="mdl-button mdl-js-button mdl-button--raised mdl-button--colored" value="Delete">
    </form>
{% endblock content %}

templates/cms/photo_form.html
{% extends 'cms/base.html' %}
{% load static form_tags %}

{% block content %}
    <div class="mdl-grid">
        <div class="mdl-cell mdl-cell--4-col">
            <form action="" method="post">
                {% csrf_token %}
                {% for field in form %}
                    <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
                        {% if field|is_checkbox %}
                        <label class="mdl-checkbox mdl-js-checkbox mdl-js-ripple-effect" for="{{ field.id_for_label }}">
                            {{ field|add_css_class:'mdl-checkbox__input' }}
                            <span class="mdl-checkbox__label">{{ field.label }}</span>
                        </label>
                        {% else %}
                        {{ field|add_css_class:'mdl-textfield__input' }}
                        <label for="{{ field.id_for_label }}" class="mdl-textfield__label">{{ field.label }}</label>
                        {% endif %}

                        {% if field.errors %}
                            {% for error in field.errors %}
                            <span class="mdl-textfield__error">{{ error }}</span>
                            {% endfor %}
                        {% endif %}
                    </div>
                {% endfor %}

                {% if object %}
                <input type="submit" class="mdl-button mdl-js-button mdl-button--raised mdl-button--colored" value="Save">
                {% else %}
                <input type="submit" class="mdl-button mdl-js-button mdl-button--raised mdl-button--colored" value="Create">
                {% endif %}
                <a class="mdl-button mdl-js-button mdl-button--raised" href="{% url 'cms:photo_list' %}">Cancel</a>
            </form>
        </div>
        <div class="mdl-cell mdl-cell--8-col">
            <div class="photo-preview">
                <img src="" alt="" data-bind="id_url" data-format="image">
            </div>
        </div>
    </div>
{% endblock content %}

{% block bodyend %}
    <script src="{% static 'js/post-preview.js' %}"></script>
{% endblock bodyend %}

templates/cms/photo_list.html
{% extends 'cms/base.html' %}

{% block content %}
    <table class="mdl-data-table mdl-shadow--2dp">
        <thead>
            <tr>
                <th>Order</th>
                <th>Change order</th>
                <th>Title</th>
                <th>Subtitle</th>
                <th>Preview</th>
                <th>Is published?</th>
                <th>Date</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
        {% for photo in photo_list %}
            <tr {% if not photo.is_published %}class="unpublished-post"{% endif %}>
                <td>{{ photo.order }}</td>
                <td>
                    <form action="{% url 'cms:set_photo_order' photo.pk %}" method="post">
                        {% csrf_token %}
                        <input type="hidden" value="-1" name="order_modifier">
                        <button type="submit" class="mdl-button mdl-js-button mdl-button--icon"><i class="material-icons">keyboard_arrow_up</i></button>
                    </form>
                    <form action="{% url 'cms:set_photo_order' photo.pk %}" method="post">
                        {% csrf_token %}
                        <input type="hidden" value="1" name="order_modifier">
                        <button type="submit" class="mdl-button mdl-js-button mdl-button--icon"><i class="material-icons">keyboard_arrow_down</i></button>
                    </form>
                </td>
                <td>{{ photo.title }}</td>
                <td>{{ photo.subtitle }}</td>
                <td><img class="photo-preview" src="{{ photo.get_flickr_preview }}" alt=""></td>
                <td>{{ photo.is_published|yesno:"Yes,No" }}</td>
                <td>{{ photo.created }}</td>
                <td>
                    <a href="{% url 'cms:update_photo' photo.pk %}">Edit</a>
                    <span>|</span>
                    <a href="{% url 'cms:delete_photo' photo.pk %}">Delete</a>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock content %}

{% block bodyend %}
<a href="{% url 'cms:new_photo' %}" class="new-post mdl-button mdl-js-button mdl-button--fab mdl-button--colored">
    <i class="material-icons">add</i>
</a>
{% endblock bodyend %}

templates/cms/post_confirm_delete.html
{% extends 'cms/base.html' %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        <p>Are you sure you want to delete the post?</p>
        <a class="mdl-button mdl-js-button mdl-button--raised" href="{% url 'cms:post_list' %}">Cancel</a>
        <input type="submit" class="mdl-button mdl-js-button mdl-button--raised mdl-button--colored" value="Delete">
    </form>
{% endblock content %}

templates/cms/post_form.html
{% extends 'cms/base.html' %}
{% load static form_tags %}

{% block content %}
    <div class="mdl-grid">
        <div class="mdl-cell mdl-cell--4-col">
            <form action="" method="post">
                {% csrf_token %}
                {% for field in form %}
                    <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
                        {% if field|is_checkbox %}
                        <label class="mdl-checkbox mdl-js-checkbox mdl-js-ripple-effect" for="{{ field.id_for_label }}">
                            {{ field|add_css_class:'mdl-checkbox__input' }}
                            <span class="mdl-checkbox__label">{{ field.label }}</span>
                        </label>
                        {% else %}
                        {{ field|add_css_class:'mdl-textfield__input' }}
                        <label for="{{ field.id_for_label }}" class="mdl-textfield__label">{{ field.label }}</label>
                        {% endif %}

                        {% if field.errors %}
                            {% for error in field.errors %}
                            <span class="mdl-textfield__error">{{ error }}</span>
                            {% endfor %}
                        {% endif %}
                    </div>
                {% endfor %}

                {% if object %}
                <input type="submit" class="mdl-button mdl-js-button mdl-button--raised mdl-button--colored" value="Save">
                {% else %}
                <input type="submit" class="mdl-button mdl-js-button mdl-button--raised mdl-button--colored" value="Create">
                {% endif %}
                <a class="mdl-button mdl-js-button mdl-button--raised" href="{% url 'cms:post_list' %}">Cancel</a>
            </form>
        </div>
        <div class="mdl-cell mdl-cell--8-col">
            <div class="post-preview">
                <h1 data-bind="id_title" data-format="text">Title</h1>
                <div data-bind="id_body" data-format="markdown">Body</div>
            </div>
        </div>
    </div>
{% endblock content %}

{% block bodyend %}
    <script src="{% static 'vendor/marked/marked.min.js' %}"></script>
    <script src="{% static 'js/post-preview.js' %}"></script>
{% endblock bodyend %}

templates/cms/post_list.html
{% extends 'cms/base.html' %}

{% block content %}
    <table class="mdl-data-table mdl-shadow--2dp">
        <thead>
            <tr>
                <th>Title</th>
                <th>Is published?</th>
                <th>Date</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
        {% for post in post_list %}
            <tr {% if not post.is_published %}class="unpublished-post"{% endif %}>
                <td>{{ post.title }}</td>
                <td>{% if post.is_published %}Yes{% else %}No{% endif %}</td>
                <td>{{ post.created }}</td>
                <td>
                    <a href="{% url 'cms:update_post' post.pk %}">Edit</a>
                    <span>|</span>
                    <a href="{% url 'cms:delete_post' post.pk %}">Delete</a>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock content %}

{% block bodyend %}
<a href="{% url 'cms:new_post' %}" class="new-post mdl-button mdl-js-button mdl-button--fab mdl-button--colored">
    <i class="material-icons">add</i>
</a>
{% endblock bodyend %}